### ISSUE TITLE
非常喜欢你这个插件 想求助帮忙修改一下

### ISSUE THREAD

**Issue by woocy** [shangZhengXie/vscode-console-helper#1]
执行删除所有console的时候  会留下空白行 能否把空白行一起删除
可不可以自定义console的文案

**Comment by shangZhengXie** [comment]
@woocy  非常感谢你的 issue，我会尽快支持~

**Comment by shangZhengXie** [comment]
@woocy hi 已更新删除 log 时删除整行，自定义 console.log 列入 TODO 中了，之后会进行更新~

**Comment by shangZhengXie** [comment]
@woocy 自定义 console 的文案功能已更新
